// Local-only integration checks. Requires an empty test database.
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const origin = process.env.TEST_ORIGIN || 'http://localhost:3000';
assert.ok(['localhost', '127.0.0.1'].includes(new URL(origin).hostname));
const password = process.env.TEST_PASSWORD || `Test-${randomUUID()}`;
const setupToken = process.env.TEST_SETUP_TOKEN;
assert.ok(setupToken?.length >= 32, 'TEST_SETUP_TOKEN must match the server SETUP_TOKEN');
let adminCookie = '';
async function request(path, { body, cookie = '', method = body ? 'POST' : 'GET', owner = false, expected = 200 } = {}) {
  const response = await fetch(origin + path, { method, redirect: 'manual', headers: { Origin: origin, ...(body ? { 'Content-Type': 'application/json' } : {}), ...(cookie ? { Cookie: cookie } : {}) }, body: body ? JSON.stringify({ ...body, ...(owner ? { setupToken } : {}) }) : undefined });
  const text = await response.text();
  assert.equal(response.status, expected, `${method} ${path}: ${text.slice(0, 250)}`);
  return { body: text ? JSON.parse(text) : {}, cookie: response.headers.get('set-cookie')?.split(';')[0] || '' };
}
await request('/api/audit', { expected: 401 });
await request('/api/access/admin', { expected: 401 });
await request('/api/workspace/drafts', { expected: 401 });
await request('/api/access/setup', { body: { password }, expected: 403 });
const setup = await request('/api/access/setup', { body: { password }, owner: true });
adminCookie = setup.cookie;
assert.ok(adminCookie);
await request('/api/access/setup', { body: { password }, owner: true, expected: 403 });
const me = await request('/api/access/me', { cookie: adminCookie });
assert.equal(me.body.user.username, 'technology');
assert.equal(me.body.user.isAdmin, true);
await request('/api/access/login', { body: { username: 'technology', password: 'wrong-password' }, expected: 401 });
await request('/api/access/login', { body: { username: 'technology', password } });
console.log('PASS: protected endpoints, setup-key protection, password sign-in');
await request('/api/access/users', { cookie: adminCookie, body: { name: 'Marketing test', username: 'marketing-test', password, roleId: 'editor' } });
await request('/api/access/users', { cookie: adminCookie, body: { name: 'Viewer test', username: 'viewer-test', password, roleId: 'viewer' } });
let marketing = (await request('/api/access/login', { body: { username: 'marketing-test', password } })).cookie;
await request('/api/access/admin', { cookie: marketing, expected: 403 });
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'announcement.create' }, expected: 403 });
marketing = (await request('/api/access/password', { cookie: marketing, body: { currentPassword: password, password: password + '-new' } })).cookie;
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'announcement.create', template: 'general' } });
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'announcement.send' }, expected: 403 });
await request('/api/access/users', { cookie: marketing, body: {}, expected: 403 });
await request('/api/audit', { cookie: marketing, body: {}, expected: 403 });
await request('/api/workspace/vendors', { cookie: marketing, body: { vendors: [] }, expected: 403 });
console.log('PASS: temporary password change and editor permission enforcement');
const draft = { id: 'smoke-draft', name: 'Access test', template: 'general', generalMessage: { en: 'Test', ar: 'اختبار' } };
await request('/api/workspace/drafts', { cookie: marketing, body: draft });
assert.equal((await request('/api/workspace/drafts', { cookie: marketing })).body.drafts.length, 1);
assert.equal((await request('/api/workspace/drafts', { cookie: adminCookie })).body.drafts.length, 0);
await request('/api/workspace/drafts', { cookie: marketing, body: { id: draft.id }, method: 'DELETE' });
assert.equal((await request('/api/workspace/drafts', { cookie: marketing })).body.drafts.length, 0);
console.log('PASS: persistent drafts and department isolation');
const list = (await request('/api/access/admin', { cookie: adminCookie })).body;
const target = list.users.find(u => u.username === 'marketing-test');
await request('/api/access/users', { cookie: adminCookie, body: { ...target, active: false } });
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'announcement.create' }, expected: 401 });
await request('/api/access/login', { body: { username: 'marketing-test', password: password + '-new' }, expected: 401 });
await request('/api/access/roles', { cookie: adminCookie, body: { id: 'admin', name: 'Changed', permissions: [] }, expected: 403 });
await request('/api/access/users', { cookie: adminCookie, body: { ...me.body.user, active: false }, expected: 400 });
const csrf = await fetch(origin + '/api/access/users', { method: 'POST', headers: { Origin: 'https://other.example', Cookie: adminCookie, 'Content-Type': 'application/json' }, body: '{}' });
assert.equal(csrf.status, 403);
console.log('PASS: disabled account revocation, admin protection, cross-origin rejection');
await request('/api/access/roles', { cookie: adminCookie, body: { name: 'General only', description: 'Local test role', permissions: ['builder.view', 'announcement.create', 'announcement.edit', 'drafts.manage', 'template.general', 'export.png'] } });
const custom = (await request('/api/access/admin', { cookie: adminCookie })).body.roles.find(r => r.name === 'General only');
await request('/api/access/users', { cookie: adminCookie, body: { ...target, roleId: custom.id, active: true } });
await request('/api/access/reset-password', { cookie: adminCookie, body: { id: target.id, password: password + '-reset' } });
marketing = (await request('/api/access/login', { body: { username: 'marketing-test', password: password + '-reset' } })).cookie;
marketing = (await request('/api/access/password', { cookie: marketing, body: { currentPassword: password + '-reset', password: password + '-final' } })).cookie;
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'export.png', template: 'general' } });
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'export.png', template: 'service' }, expected: 403 });
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'export.pdf', template: 'general' }, expected: 403 });
await request('/api/workspace/drafts', { cookie: marketing, body: { ...draft, template: 'service' }, expected: 403 });
await request('/api/access/roles', { cookie: adminCookie, body: { ...custom, permissions: ['dashboard.view'] } });
await request('/api/access/authorize', { cookie: marketing, body: { permission: 'export.png' }, expected: 401 });
console.log('PASS: custom roles, password reset, template/export restrictions, role-change revocation');
await request('/api/access/roles', { method: 'DELETE', body: { id: 'viewer' }, expected: 401 });
await request('/api/access/roles', { cookie: adminCookie, method: 'DELETE', body: { id: 'admin' }, expected: 403 });
await request('/api/access/roles', { cookie: adminCookie, method: 'DELETE', body: { id: 'viewer' }, expected: 409 });
await request('/api/access/roles', { cookie: adminCookie, body: { name: 'Disposable test role', description: '', permissions: ['dashboard.view'] } });
const disposable = (await request('/api/access/admin', { cookie: adminCookie })).body.roles.find(r => r.name === 'Disposable test role');
assert.equal(disposable.assignedCount, 0);
await request('/api/access/roles', { cookie: adminCookie, method: 'DELETE', body: { id: disposable.id } });
await request('/api/access/roles', { cookie: adminCookie, method: 'DELETE', body: { id: disposable.id }, expected: 404 });
assert.ok(!(await request('/api/access/admin', { cookie: adminCookie })).body.roles.some(r => r.id === disposable.id));
console.log('PASS: role deletion, assigned-role protection and administrator protection');
await request('/api/access/logout', { cookie: adminCookie, method: 'POST', expected: 303 });
await request('/api/access/admin', { cookie: adminCookie, expected: 401 });
console.log('PASS: sign-out invalidates the session');
adminCookie = (await request('/api/access/login', { body: { username: 'technology', password } })).cookie;
await request('/api/workspace/drafts', { cookie: adminCookie, body: { ...draft, id: 'persistence-check' } });
await request('/api/access/logout', { cookie: adminCookie, method: 'POST', expected: 303 });
